### ISSUE TITLE
Can't load the nsPopover module

### ISSUE THREAD

**Issue by dennisa** [nohros/nsPopover#76]
I can't load the module:

here is my definition

var MyApp = angular.module('MyApp', [
  'angulartics.google.tagmanager','ngTouch', 'nsPopover',
  'ngRoute', 'ngCookies', 'ngSanitize', 'ui.bootstrap', 'ngAnimate','angular-carousel'
]);

Error: [$injector:modulerr] Failed to instantiate module nsPopover due to:
Error: [$injector:nomod] Module 'nsPopover' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.28/$injector/nomod?p0=nsPopover
    at http://0.0.0.0:9000/bower_components/angular/angular.js:78:12
    at http://0.0.0.0:9000/bower_components/angular/angular.js:1677:17
    at ensure (http://0.0.0.0:9000/bower_components/angular/angular.js:1601:38)
    at module (http://0.0.0.0:9000/bower_components/angular/angular.js:1675:14)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:3877:22
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:325:18)
    at loadModules (http://0.0.0.0:9000/bower_components/angular/angular.js:3871:5)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:3878:40
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:325:18)
    at loadModules (http://0.0.0.0:9000/bower_components/angular/angular.js:3871:5)

**Comment by Fen1kz** [comment]
nsPopover should be included below angular.js script
